rewrite to support variable number of DCs

diff --git a/roles/common/files/prepDisks b/roles/common/files/prepDisks
--- a/roles/common/files/prepDisks
+++ b/roles/common/files/prepDisks
@@ -1,30 +1,70 @@
 #!/bin/bash
 
-set -e
+# set -e
 
 if [ "$1" != "--format" ]; then
-	echo "Usage: $0 --format"
-	echo "  Will create a single partition and formats each disk that has no existing partitions defined yet"
-	exit 2
+        echo "Usage: $0 --format"
+        echo "  Will create a single partition and formats any disk found on the system excluding OS drives (yes, ANY device other than OS!)"
+        exit 2
 fi
 
 which sgdisk >/dev/null || exit 1
 
 n=1
-DEVS=($( lsblk --output NAME --nodeps --noheadings ))
+tools_directory="/root/CloudianTools"
+function get_datadrives() {
+        ls /sys/block/ | egrep -vw '[md][md]-?[0-9]+' | while read dev; do
+        skip=false
+        # check if we exist in mdraid
+        egrep -q "${dev}[0-9]+" /proc/mdstat 2>/dev/null && skip=true
+        # skip LVM PV
+        pvdisplay 2>/dev/null | egrep -q "^\s+PV Name\s+\/dev\/${dev}[0-9]+$" && skip=true
+        # check if UUID is present in fstab
+        ls /dev/${dev}* | while read ddev; do
+                duuid=$(blkid -o value -s UUID $ddev)
+                egrep -q "$duuid" /etc/fstab && skip=true
+        done
+        [[ ${skip} = true ]] || echo $dev
+done
+}
 
+# make sure we clean up any left overs
+ls -d /cloudian* 2>/dev/null | while read mp; do
+        umount $mp 2>/dev/null
+        sleep 0.5
+        rmdir $mp
+done
+# remove fstab entries
+sed -i -r -e "/^UUID=.+\s+\/cloudian[0-9]+\s+.+$/d" /etc/fstab
+rm ${tools_directory}/fslist.txt 2>/dev/null
+# important to run daemon-reload! Otherwise re-creating a filesystem on device
+# will cause systemd to automatically mount it even if fstab has been cleared out
+grep -q 'release 6' /etc/redhat-release || systemctl daemon-reload
+
+DEVS=($( get_datadrives ))
+_pids=()
 for dev in ${DEVS[@]}; do
-	device="/dev/${dev}"
-	dpart=${device}1
-	[[ -e ${dpart} ]] && continue
-	sgdisk -Z ${device}
-	sgdisk --new=1:2048 ${device}
-	mkfs.ext4 -q -i 8192 -m 0 -E lazy_itable_init=1,discard -O dir_index,extent,flex_bg,large_file,sparse_super,uninit_bg ${dpart}
-	mkdir /cloudian${n}
-	UUID=$( blkid -o value -s UUID ${dpart} )
-	printf 'UUID=%s\t%s\t%s\t%s\t0\t1\n' "${UUID}" "/cloudian${n}" "ext4" "defaults,rw,nosuid,noexec,nodev,noatime,data=ordered,errors=remount-ro" >> /etc/fstab
-	printf '%s\t%s\n' "${dpart}" "/cloudian${n}" >> /root/CloudianTools/fslist.txt
-	let n++
+        echo "init device $dev"
+        device="/dev/${dev}"
+        dpart=${device}1
+        # [[ -e ${dpart} ]] && continue
+        sgdisk -Z ${device}
+        sgdisk --new=1:2048 ${device}
+        ( mkfs.ext4 -q -i 8192 -m 0 -E lazy_itable_init=1,discard -O dir_index,extent,flex_bg,large_file,sparse_super,uninit_bg ${dpart} ) &
+        _pids+=(${!})
+        DEVS[${!}]=${dpart}
+done
+
+for _pid in ${_pids[@]}; do
+        wait ${_pid}
+        _dpart=${DEVS[$_pid]}
+        mkdir /cloudian${n}
+        UUID=$( blkid -o value -s UUID ${_dpart} )
+        printf 'UUID=%s\t%s\t%s\t%s\t0\t1\n' "${UUID}" "/cloudian${n}" "ext4" "defaults,rw,nosuid,noexec,nodev,noatime,noinit_itable,data=ordered,errors=remount-ro" >> /etc/fstab
+        printf '%s\t%s\n' "${_dpart}" "/cloudian${n}" >> ${tools_directory}/fslist.txt
+        let n++
 done
 
 mount -a
+
+exit 0
