Indent is 4 spaces!

diff --git a/roles/common/files/prepDisks b/roles/common/files/prepDisks
--- a/roles/common/files/prepDisks
+++ b/roles/common/files/prepDisks
@@ -3,9 +3,9 @@
 # set -e
 
 if [ "$1" != "--format" ]; then
-        echo "Usage: $0 --format"
-        echo "  Will create a single partition and formats any disk found on the system excluding OS drives (yes, ANY device other than OS!)"
-        exit 2
+    echo "Usage: $0 --format"
+    echo "  Will create a single partition and formats any disk found on the system excluding OS drives (yes, ANY device other than OS!)"
+    exit 2
 fi
 
 which sgdisk >/dev/null || exit 1
@@ -47,9 +47,9 @@ function get_datadrives() {
 
 # make sure we clean up any left overs
 ls -d /cloudian* 2>/dev/null | while read mp; do
-        umount $mp 2>/dev/null
-        sleep 0.5
-        rmdir $mp
+    umount $mp 2>/dev/null
+    sleep 0.5
+    rmdir $mp
 done
 
 # remove fstab entries
@@ -65,25 +65,25 @@ fi
 DEVS=($( get_datadrives ))
 _pids=()
 for dev in ${DEVS[@]}; do
-        echo "init device $dev"
-        device="/dev/${dev}"
-        dpart=${device}1
-        # [[ -e ${dpart} ]] && continue
-        sgdisk -Z ${device}
-        sgdisk --new=1:2048 ${device}
-        ( mkfs.ext4 -q -i 8192 -m 0 -E lazy_itable_init=1,discard -O dir_index,extent,flex_bg,large_file,sparse_super,uninit_bg ${dpart} ) &
-        _pids+=(${!})
-        DEVS[${!}]=${dpart}
+    echo "init device $dev"
+    device="/dev/${dev}"
+    dpart=${device}1
+    # [[ -e ${dpart} ]] && continue
+    sgdisk -Z ${device}
+    sgdisk --new=1:2048 ${device}
+    ( mkfs.ext4 -q -i 8192 -m 0 -E lazy_itable_init=1,discard -O dir_index,extent,flex_bg,large_file,sparse_super,uninit_bg ${dpart} ) &
+    _pids+=(${!})
+    DEVS[${!}]=${dpart}
 done
 
 for _pid in ${_pids[@]}; do
-        wait ${_pid}
-        _dpart=${DEVS[$_pid]}
-        mkdir /cloudian${n}
-        UUID=$( blkid -o value -s UUID ${_dpart} )
-        printf 'UUID=%s\t%s\t%s\t%s\t0\t1\n' "${UUID}" "/cloudian${n}" "ext4" "defaults,rw,nosuid,noexec,nodev,noatime,noinit_itable,data=ordered,errors=remount-ro" >> /etc/fstab
-        printf '%s\t%s\n' "${_dpart}" "/cloudian${n}" >> ${tools_directory}/fslist.txt
-        let n++
+    wait ${_pid}
+    _dpart=${DEVS[$_pid]}
+    mkdir /cloudian${n}
+    UUID=$( blkid -o value -s UUID ${_dpart} )
+    printf 'UUID=%s\t%s\t%s\t%s\t0\t1\n' "${UUID}" "/cloudian${n}" "ext4" "defaults,rw,nosuid,noexec,nodev,noatime,noinit_itable,data=ordered,errors=remount-ro" >> /etc/fstab
+    printf '%s\t%s\n' "${_dpart}" "/cloudian${n}" >> ${tools_directory}/fslist.txt
+    let n++
 done
 
 mount -a
